name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup
      run: |
        npm install -g @angular/cli
        npm ci
      env:
        CI: true
    - name: Build
      run: ng build
    - name: Deploy to staging
      if: github.ref == 'refs/heads/master'
      uses: actions/aws/cli@master
      with:
        args: s3 sync dist/ s3://calendars.worldskills.show
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
    - name: Invalidate staging
      if: github.ref == 'refs/heads/master'
      uses: actions/aws/cli@master
      with:
        args: cloudfront create-invalidation --distribution-id E2YVXBZSB5EAXR --paths /index.html
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
    - name: Deploy to production
      if: github.ref == 'refs/heads/prod'
      uses: actions/aws/cli@master
      with:
        args: s3 sync dist/ s3://calendars.worldskills.org
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
    - name: Invalidate production
      if: github.ref == 'refs/heads/prod'
      uses: actions/aws/cli@master
      with:
        args: cloudfront create-invalidation --distribution-id E2OY509NYCBMY4 --paths /index.html
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
